#!/bin/bash
# Build a custom fyne CLI with Camera2 QR scanner Java embedded.
#
# The modern fyne CLI embeds a pre-compiled DEX (classes.dex) as a base64 string
# in fyne.io/tools/cmd/fyne/internal/mobile/dex.go. We must:
#   1. Compile our patched Java code in the vendor folder → .class files with javac
#   2. Convert .class → classes.dex with d8
#   3. Clone fyne-io/tools.git
#   4. Re-generate dex.go with the new DEX bytes inside the tools repo
#   5. Build the custom fyne CLI

set -e

ENGRAM_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK_DIR="/tmp/fyne-custom-build"

# Find Android SDK
if [ -z "$ANDROID_HOME" ]; then
    if [ -d "$HOME/Android/Sdk" ]; then
        ANDROID_HOME="$HOME/Android/Sdk"
    elif [ -d "$HOME/Library/Android/sdk" ]; then
        ANDROID_HOME="$HOME/Library/Android/sdk"
    elif [ -d "/usr/lib/android-sdk" ]; then
        ANDROID_HOME="/usr/lib/android-sdk"
    else
        echo "ERROR: ANDROID_HOME is not set and could not be found in common locations."
        echo "Please set ANDROID_HOME to your Android SDK directory."
        exit 1
    fi
fi

# Find d8
D8=$(find "$ANDROID_HOME/build-tools" -name "d8" 2>/dev/null | sort -r | head -1)
if [ -z "$D8" ]; then
    echo "ERROR: d8 not found in $ANDROID_HOME/build-tools. Please install build-tools."
    exit 1
fi

# Find android.jar
ANDROID_JAR=$(find "$ANDROID_HOME/platforms" -name "android.jar" 2>/dev/null | sort -r | head -1)
if [ -z "$ANDROID_JAR" ]; then
    echo "ERROR: android.jar not found in $ANDROID_HOME/platforms. Please install a platform (e.g., android-35)."
    exit 1
fi

echo "=== Building custom fyne CLI with QR scanner support ==="
echo "  SDK Home:    $ANDROID_HOME"
echo "  android.jar: $ANDROID_JAR"
echo "  d8:          $D8"
echo ""

# Clean previous build
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/classes"
cd "$WORK_DIR"

# Compile Java → .class
echo "1/5  Compiling Java with javac..."
JAVA_DIR="$ENGRAM_DIR/internal/patches/android"
if ! javac -source 8 -target 8 \
    -classpath "$ANDROID_JAR" \
    -bootclasspath "$ANDROID_JAR" \
    -d "$WORK_DIR/classes" \
    "$JAVA_DIR"/*.java; then
    echo ""
    echo "❌ ERROR: javac compilation failed! Fix the Java errors above."
    exit 1
fi

echo "     Compiled $(find $WORK_DIR/classes -name '*.class' | wc -l) class files"

# Convert .class → classes.dex
echo "2/5  Converting to DEX with d8..."
CLASS_FILES=$(find "$WORK_DIR/classes" -name "*.class" -type f)
"$D8" --min-api 21 --output "$WORK_DIR" $CLASS_FILES 2>&1
ls -la "$WORK_DIR/classes.dex"

# Clone fyne tools repo (which replaced cmd/fyne in main repo)
echo "3/5  Cloning fyne tools repo..."
git clone --depth 1 https://github.com/fyne-io/tools.git fyne-tools 2>&1 | tail -1

# Generate new dex.go
echo "4/5  Generating dex.go with embedded DEX..."
DEX_BASE64=$(base64 -w 0 "$WORK_DIR/classes.dex")

DEX_GO="$WORK_DIR/fyne-tools/cmd/fyne/internal/mobile/dex.go"
cat > "$DEX_GO" << 'HEADER'
// Code generated by build_fyne_custom.sh. DO NOT EDIT.
package mobile
HEADER

echo -n 'var dexStr = `' >> "$DEX_GO"
echo "$DEX_BASE64" | fold -w 70 | while IFS= read -r line; do
    echo -n "$line" >> "$DEX_GO"
done
echo '`' >> "$DEX_GO"

echo "     dex.go size: $(wc -c < "$DEX_GO") bytes"

# Build the custom fyne CLI
echo "5/5  Building fyne CLI..."
cd "$WORK_DIR/fyne-tools/cmd/fyne"
go build -o "$ENGRAM_DIR/bin/fyne-custom" . 2>&1

echo ""
echo "✅ Custom fyne CLI built: $ENGRAM_DIR/bin/fyne-custom"
echo ""

# Verify
if strings "$ENGRAM_DIR/bin/fyne-custom" | grep -q "startQRCamera" 2>/dev/null; then
    echo "✅ Verified: startQRCamera is in the binary"
else
    echo "ℹ  DEX is binary-encoded (startQRCamera embedded in compiled DEX)"
fi

echo ""
echo "Usage:"
echo "  cd $ENGRAM_DIR"
echo "  ./bin/fyne-custom package --os android --app-id com.derofdn.engram"
