// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed connect.png
var resourceConnectPngData []byte
var resourceConnectPng = &fyne.StaticResource{
	StaticName:    "connect.png",
	StaticContent: resourceConnectPngData,
}
