// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed favs.png
var resourceFavsPngData []byte
var resourceFavsPng = &fyne.StaticResource{
	StaticName:    "favs.png",
	StaticContent: resourceFavsPngData,
}
