// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/tela.png
var resourceTelaPngData []byte
var resourceTelaPng = &fyne.StaticResource{
	StaticName:    "tela.png",
	StaticContent: resourceTelaPngData,
}
