// Code generated by lutgen; DO NOT EDIT.

package astrobwt

import "math/bits"

// pureOpCount is the number of ops that are a function of a single byte.
const pureOpCount = 149

// pureOpSet reports which ops pureOp can evaluate.
var pureOpSet = [256]bool{
	2:   true,
	4:   true,
	6:   true,
	7:   true,
	8:   true,
	10:  true,
	12:  true,
	14:  true,
	16:  true,
	18:  true,
	19:  true,
	22:  true,
	24:  true,
	25:  true,
	26:  true,
	28:  true,
	31:  true,
	32:  true,
	33:  true,
	34:  true,
	36:  true,
	37:  true,
	38:  true,
	41:  true,
	42:  true,
	44:  true,
	46:  true,
	48:  true,
	49:  true,
	50:  true,
	52:  true,
	53:  true,
	55:  true,
	56:  true,
	57:  true,
	59:  true,
	61:  true,
	63:  true,
	65:  true,
	66:  true,
	67:  true,
	69:  true,
	71:  true,
	73:  true,
	76:  true,
	77:  true,
	78:  true,
	79:  true,
	81:  true,
	83:  true,
	84:  true,
	86:  true,
	87:  true,
	88:  true,
	89:  true,
	90:  true,
	95:  true,
	96:  true,
	97:  true,
	98:  true,
	99:  true,
	100: true,
	101: true,
	102: true,
	104: true,
	105: true,
	106: true,
	107: true,
	110: true,
	111: true,
	112: true,
	113: true,
	114: true,
	118: true,
	121: true,
	122: true,
	125: true,
	126: true,
	128: true,
	129: true,
	130: true,
	131: true,
	135: true,
	137: true,
	139: true,
	141: true,
	144: true,
	145: true,
	147: true,
	151: true,
	152: true,
	153: true,
	156: true,
	157: true,
	158: true,
	160: true,
	162: true,
	163: true,
	164: true,
	166: true,
	167: true,
	170: true,
	171: true,
	172: true,
	173: true,
	174: true,
	175: true,
	179: true,
	181: true,
	183: true,
	185: true,
	186: true,
	188: true,
	191: true,
	192: true,
	196: true,
	197: true,
	198: true,
	200: true,
	201: true,
	205: true,
	206: true,
	207: true,
	208: true,
	209: true,
	210: true,
	211: true,
	213: true,
	217: true,
	218: true,
	220: true,
	224: true,
	225: true,
	228: true,
	229: true,
	232: true,
	233: true,
	235: true,
	237: true,
	238: true,
	243: true,
	244: true,
	245: true,
	246: true,
	247: true,
	248: true,
	249: true,
	251: true,
	252: true,
}

func isPureOp(op byte) bool { return pureOpSet[op] }

// pureOp applies op's byte transform to x. Only valid when isPureOp(op).
// Bodies are lifted verbatim from the switch in pow.go with step_3[i] renamed to x.
func pureOp(op, x byte) byte {
	switch op {
	case 2:
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.Reverse8(x)
		x = x << (x & 3)
		x = x ^ byte(bits.OnesCount8(x))
	case 4:
		x = ^x
		x = x >> (x & 3)
		x = bits.RotateLeft8(x, int(x))
		x -= (x ^ 97)
	case 6:
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 3)
		x = ^x
		x -= (x ^ 97)
	case 7:
		x += x
		x = bits.RotateLeft8(x, int(x))
		x = x ^ byte(bits.OnesCount8(x))
		x = ^x
	case 8:
		x = ^x
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 5)
		x = x << (x & 3)
	case 10:
		x = ^x
		x *= x
		x = bits.RotateLeft8(x, 3)
		x *= x
	case 12:
		x = x ^ bits.RotateLeft8(x, 2)
		x *= x
		x = x ^ bits.RotateLeft8(x, 2)
		x = ^x
	case 14:
		x = x >> (x & 3)
		x = x << (x & 3)
		x *= x
		x = x << (x & 3)
	case 16:
		x = x ^ bits.RotateLeft8(x, 4)
		x *= x
		x = bits.RotateLeft8(x, 1)
		x = ^x
	case 18:
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 5)
	case 19:
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, 5)
		x = x << (x & 3)
		x += x
	case 22:
		x = x << (x & 3)
		x = bits.Reverse8(x)
		x *= x
		x = bits.RotateLeft8(x, 1)
	case 24:
		x += x
		x = x >> (x & 3)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 5)
	case 25:
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, int(x))
		x -= (x ^ 97)
	case 26:
		x *= x
		x = x ^ byte(bits.OnesCount8(x))
		x += x
		x = bits.Reverse8(x)
	case 28:
		x = x << (x & 3)
		x += x
		x += x
		x = bits.RotateLeft8(x, 5)
	case 31:
		x = ^x
		x = x ^ bits.RotateLeft8(x, 2)
		x = x << (x & 3)
		x *= x
	case 32:
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 2)
	case 33:
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.Reverse8(x)
		x *= x
	case 34:
		x -= (x ^ 97)
		x = x << (x & 3)
		x = x << (x & 3)
		x -= (x ^ 97)
	case 36:
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 1)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 1)
	case 37:
		x = bits.RotateLeft8(x, int(x))
		x = x >> (x & 3)
		x = x >> (x & 3)
		x *= x
	case 38:
		x = x >> (x & 3)
		x = bits.RotateLeft8(x, 3)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, int(x))
	case 41:
		x = bits.RotateLeft8(x, 5)
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 4)
	case 42:
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, int(x))
	case 44:
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, int(x))
	case 46:
		x = x ^ byte(bits.OnesCount8(x))
		x += x
		x = bits.RotateLeft8(x, 5)
		x = x ^ bits.RotateLeft8(x, 4)
	case 48:
		x = bits.RotateLeft8(x, int(x))
		x = ^x
		x = ^x
		x = bits.RotateLeft8(x, 5)
	case 49:
		x = x ^ byte(bits.OnesCount8(x))
		x += x
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
	case 50:
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 3)
		x += x
		x = bits.RotateLeft8(x, 1)
	case 52:
		x = bits.RotateLeft8(x, int(x))
		x = x >> (x & 3)
		x = ^x
		x = x ^ byte(bits.OnesCount8(x))
	case 53:
		x += x
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 4)
	case 55:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 1)
	case 56:
		x = x ^ bits.RotateLeft8(x, 2)
		x *= x
		x = ^x
		x = bits.RotateLeft8(x, 1)
	case 57:
		x = bits.RotateLeft8(x, int(x))
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 3)
		x = bits.Reverse8(x)
	case 59:
		x = bits.RotateLeft8(x, 1)
		x *= x
		x = bits.RotateLeft8(x, int(x))
		x = ^x
	case 61:
		x = bits.RotateLeft8(x, 5)
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, 5)
	case 63:
		x = bits.RotateLeft8(x, 5)
		x = x ^ byte(bits.OnesCount8(x))
		x -= (x ^ 97)
		x += x
	case 65:
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x *= x
	case 66:
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 1)
	case 67:
		x = bits.RotateLeft8(x, 1)
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
	case 69:
		x += x
		x *= x
		x = bits.Reverse8(x)
		x = x >> (x & 3)
	case 71:
		x = bits.RotateLeft8(x, 5)
		x = ^x
		x *= x
		x = x << (x & 3)
	case 73:
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 5)
		x -= (x ^ 97)
	case 76:
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
		x = x >> (x & 3)
	case 77:
		x = bits.RotateLeft8(x, 3)
		x += x
		x = x << (x & 3)
		x = x ^ byte(bits.OnesCount8(x))
	case 78:
		x = bits.RotateLeft8(x, int(x))
		x = bits.Reverse8(x)
		x *= x
		x -= (x ^ 97)
	case 79:
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 2)
		x += x
		x *= x
	case 81:
		x = x ^ bits.RotateLeft8(x, 4)
		x = x << (x & 3)
		x = bits.RotateLeft8(x, int(x))
		x = x ^ byte(bits.OnesCount8(x))
	case 83:
		x = x << (x & 3)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 3)
		x = bits.Reverse8(x)
	case 84:
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, 1)
		x = x << (x & 3)
		x += x
	case 86:
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 4)
		x = ^x
	case 87:
		x += x
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 4)
		x += x
	case 88:
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 1)
		x *= x
		x = ^x
	case 89:
		x += x
		x *= x
		x = ^x
		x = x ^ bits.RotateLeft8(x, 2)
	case 90:
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 1)
		x = x >> (x & 3)
	case 95:
		x = bits.RotateLeft8(x, 1)
		x = ^x
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 5)
	case 96:
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 1)
	case 97:
		x = bits.RotateLeft8(x, 1)
		x = x << (x & 3)
		x = x ^ byte(bits.OnesCount8(x))
		x = x >> (x & 3)
	case 98:
		x = x ^ bits.RotateLeft8(x, 4)
		x = x << (x & 3)
		x = x >> (x & 3)
		x = x ^ bits.RotateLeft8(x, 4)
	case 99:
		x = x ^ bits.RotateLeft8(x, 4)
		x -= (x ^ 97)
		x = bits.Reverse8(x)
		x = x >> (x & 3)
	case 100:
		x = bits.RotateLeft8(x, int(x))
		x = x << (x & 3)
		x = bits.Reverse8(x)
		x = x ^ byte(bits.OnesCount8(x))
	case 101:
		x = x >> (x & 3)
		x = x ^ byte(bits.OnesCount8(x))
		x = x >> (x & 3)
		x = ^x
	case 102:
		x = bits.RotateLeft8(x, 3)
		x -= (x ^ 97)
		x += x
		x = bits.RotateLeft8(x, 3)
	case 104:
		x = bits.Reverse8(x)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 5)
		x += x
	case 105:
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 2)
	case 106:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 1)
		x *= x
	case 107:
		x = x >> (x & 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 1)
	case 110:
		x += x
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x >> (x & 3)
	case 111:
		x *= x
		x = bits.Reverse8(x)
		x *= x
		x = x >> (x & 3)
	case 112:
		x = bits.RotateLeft8(x, 3)
		x = ^x
		x = bits.RotateLeft8(x, 5)
		x -= (x ^ 97)
	case 113:
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 1)
		x = x ^ byte(bits.OnesCount8(x))
		x = ^x
	case 114:
		x = bits.RotateLeft8(x, 1)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, int(x))
		x = ^x
	case 118:
		x = x >> (x & 3)
		x += x
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 5)
	case 121:
		x = x >> (x & 3)
		x += x
		x = x ^ byte(bits.OnesCount8(x))
		x *= x
	case 122:
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, int(x))
		x = bits.RotateLeft8(x, 5)
		x = x ^ bits.RotateLeft8(x, 2)
	case 125:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 2)
		x += x
		x = x >> (x & 3)
	case 126:
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 5)
		x = bits.Reverse8(x)
	case 128:
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
	case 129:
		x = ^x
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ byte(bits.OnesCount8(x))
		x = x >> (x & 3)
	case 130:
		x = x >> (x & 3)
		x = bits.RotateLeft8(x, int(x))
		x = bits.RotateLeft8(x, 1)
		x = x ^ bits.RotateLeft8(x, 4)
	case 131:
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, 1)
		x = x ^ byte(bits.OnesCount8(x))
		x *= x
	case 135:
		x = x >> (x & 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x += x
		x = bits.Reverse8(x)
	case 137:
		x = bits.RotateLeft8(x, 5)
		x = x >> (x & 3)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, int(x))
	case 139:
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 3)
	case 141:
		x = bits.RotateLeft8(x, 1)
		x -= (x ^ 97)
		x = x ^ byte(bits.OnesCount8(x))
		x += x
	case 144:
		x = bits.RotateLeft8(x, int(x))
		x = x << (x & 3)
		x = ^x
		x = bits.RotateLeft8(x, int(x))
	case 145:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 4)
	case 147:
		x = ^x
		x = x << (x & 3)
		x = x ^ bits.RotateLeft8(x, 4)
		x *= x
	case 151:
		x += x
		x = x << (x & 3)
		x *= x
		x = x << (x & 3)
	case 152:
		x = x >> (x & 3)
		x = ^x
		x = x << (x & 3)
		x = x ^ bits.RotateLeft8(x, 2)
	case 153:
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 3)
		x = ^x
		x = ^x
	case 156:
		x = x >> (x & 3)
		x = x >> (x & 3)
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, 1)
	case 157:
		x = x >> (x & 3)
		x = x << (x & 3)
		x = bits.RotateLeft8(x, int(x))
		x = bits.RotateLeft8(x, 1)
	case 158:
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 3)
		x += x
		x = bits.RotateLeft8(x, 1)
	case 160:
		x = x >> (x & 3)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 3)
	case 162:
		x *= x
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 2)
		x -= (x ^ 97)
	case 163:
		x = x << (x & 3)
		x -= (x ^ 97)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 1)
	case 164:
		x *= x
		x = x ^ byte(bits.OnesCount8(x))
		x -= (x ^ 97)
		x = ^x
	case 166:
		x = bits.RotateLeft8(x, 3)
		x += x
		x = x ^ bits.RotateLeft8(x, 2)
		x = ^x
	case 167:
		x = ^x
		x = ^x
		x *= x
		x = x >> (x & 3)
	case 170:
		x -= (x ^ 97)
		x = bits.Reverse8(x)
		x -= (x ^ 97)
		x *= x
	case 171:
		x = bits.RotateLeft8(x, 3)
		x -= (x ^ 97)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.Reverse8(x)
	case 172:
		x = x ^ bits.RotateLeft8(x, 4)
		x -= (x ^ 97)
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 1)
	case 173:
		x = ^x
		x = x << (x & 3)
		x *= x
		x += x
	case 174:
		x = ^x
		x = bits.RotateLeft8(x, int(x))
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ byte(bits.OnesCount8(x))
	case 175:
		x = bits.RotateLeft8(x, 3)
		x -= (x ^ 97)
		x *= x
		x = bits.RotateLeft8(x, 5)
	case 179:
		x = x ^ bits.RotateLeft8(x, 2)
		x += x
		x = x >> (x & 3)
		x = bits.Reverse8(x)
	case 181:
		x = ^x
		x = x << (x & 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
	case 183:
		x += x
		x -= (x ^ 97)
		x -= (x ^ 97)
		x *= x
	case 185:
		x = ^x
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 5)
		x = x >> (x & 3)
	case 186:
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 4)
		x -= (x ^ 97)
		x = x >> (x & 3)
	case 188:
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 4)
	case 191:
		x += x
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, int(x))
		x = x >> (x & 3)
	case 192:
		x += x
		x = x << (x & 3)
		x += x
		x *= x
	case 196:
		x = bits.RotateLeft8(x, 3)
		x = bits.Reverse8(x)
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 1)
	case 197:
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, int(x))
		x *= x
		x *= x
	case 198:
		x = x >> (x & 3)
		x = x >> (x & 3)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 1)
	case 200:
		x = x >> (x & 3)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.Reverse8(x)
		x = bits.Reverse8(x)
	case 201:
		x = bits.RotateLeft8(x, 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ bits.RotateLeft8(x, 4)
		x = ^x
	case 205:
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ bits.RotateLeft8(x, 4)
		x = x << (x & 3)
		x += x
	case 206:
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.Reverse8(x)
		x = bits.Reverse8(x)
		x = x ^ byte(bits.OnesCount8(x))
	case 207:
		x = bits.RotateLeft8(x, 5)
		x = bits.RotateLeft8(x, 3)
		x = x ^ byte(bits.OnesCount8(x))
		x = x ^ byte(bits.OnesCount8(x))
	case 208:
		x += x
		x += x
		x = x >> (x & 3)
		x = bits.RotateLeft8(x, 3)
	case 209:
		x = bits.RotateLeft8(x, 5)
		x = bits.Reverse8(x)
		x = x ^ byte(bits.OnesCount8(x))
		x -= (x ^ 97)
	case 210:
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, int(x))
		x = bits.RotateLeft8(x, 5)
		x = ^x
	case 211:
		x = x ^ bits.RotateLeft8(x, 4)
		x += x
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, int(x))
	case 213:
		x += x
		x = x << (x & 3)
		x = bits.RotateLeft8(x, 3)
		x -= (x ^ 97)
	case 217:
		x = bits.RotateLeft8(x, 5)
		x += x
		x = bits.RotateLeft8(x, 1)
		x = x ^ bits.RotateLeft8(x, 4)
	case 218:
		x = bits.Reverse8(x)
		x = ^x
		x *= x
		x -= (x ^ 97)
	case 220:
		x = bits.RotateLeft8(x, 1)
		x = x << (x & 3)
		x = bits.Reverse8(x)
		x = x << (x & 3)
	case 224:
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 1)
		x = bits.RotateLeft8(x, 3)
		x = x << (x & 3)
	case 225:
		x = ^x
		x = x >> (x & 3)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 3)
	case 228:
		x += x
		x = x >> (x & 3)
		x += x
		x = x ^ byte(bits.OnesCount8(x))
	case 229:
		x = bits.RotateLeft8(x, 3)
		x = bits.RotateLeft8(x, int(x))
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ byte(bits.OnesCount8(x))
	case 232:
		x *= x
		x *= x
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, 5)
	case 233:
		x = bits.RotateLeft8(x, 1)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 3)
		x = x ^ byte(bits.OnesCount8(x))
	case 235:
		x = x ^ bits.RotateLeft8(x, 2)
		x *= x
		x = bits.RotateLeft8(x, 3)
		x = ^x
	case 237:
		x = bits.RotateLeft8(x, 5)
		x = x << (x & 3)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 3)
	case 238:
		x += x
		x += x
		x = bits.RotateLeft8(x, 3)
		x -= (x ^ 97)
	case 243:
		x = bits.RotateLeft8(x, 5)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 1)
	case 244:
		x = ^x
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.Reverse8(x)
		x = bits.RotateLeft8(x, 5)
	case 245:
		x -= (x ^ 97)
		x = bits.RotateLeft8(x, 5)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x >> (x & 3)
	case 246:
		x += x
		x = bits.RotateLeft8(x, 1)
		x = x >> (x & 3)
		x += x
	case 247:
		x = bits.RotateLeft8(x, 5)
		x = x ^ bits.RotateLeft8(x, 2)
		x = bits.RotateLeft8(x, 5)
		x = ^x
	case 248:
		x = ^x
		x -= (x ^ 97)
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.RotateLeft8(x, 5)
	case 249:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 4)
		x = bits.RotateLeft8(x, int(x))
	case 251:
		x += x
		x = x ^ byte(bits.OnesCount8(x))
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 2)
	case 252:
		x = bits.Reverse8(x)
		x = x ^ bits.RotateLeft8(x, 4)
		x = x ^ bits.RotateLeft8(x, 2)
		x = x << (x & 3)
	}
	return x
}
